"""영속성 포트. 유스케이스는 저장 기술(PostGIS/S3)을 알지 못한다."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from stage_scout.domain.model.event import PerformanceEvent
from stage_scout.domain.model.layout import LayoutPlan
from stage_scout.domain.model.survey import SitePhoto, TerrainAnalysis
from stage_scout.domain.model.venue import VenueCandidate


class VenueRepository(Protocol):
    def save(self, venue: VenueCandidate) -> None: ...
    def find_by_id(self, venue_id: UUID) -> VenueCandidate | None: ...
    def find_all_for_event(self, event_id: UUID) -> list[VenueCandidate]: ...


class EventRepository(Protocol):
    def save(self, event: PerformanceEvent) -> None: ...
    def find_by_id(self, event_id: UUID) -> PerformanceEvent | None: ...


class PhotoRepository(Protocol):
    def save(self, photo: SitePhoto) -> None: ...
    def find_by_venue(self, venue_id: UUID) -> list[SitePhoto]: ...


class TerrainRepository(Protocol):
    def save(self, analysis: TerrainAnalysis) -> None: ...
    def find_by_venue(self, venue_id: UUID) -> TerrainAnalysis | None: ...


class LayoutRepository(Protocol):
    def save(self, plan: LayoutPlan) -> None: ...
    def find_by_id(self, plan_id: UUID) -> LayoutPlan | None: ...
    def find_by_event(self, event_id: UUID) -> list[LayoutPlan]: ...
